# Change these first
owner: m1rc0
repo: starfleetuptime

sites:
  - name: Wardenburg Social Mastodon
    url: https://masto.wardenburg.social
  - name: Wardenburg Social PeerTube
    url: https://tube.wardenburg.social
  - name: Wardenburg Social Synapse (Matrix) Server
    url: https://matrix.ocrim.de
  - name: Wardenburg Social Nextcloud
    url: https://cloud.wardenburg.social

status-website:
  baseUrl: /starfleetuptime
  cname: uptime.wardenburg.social
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Starfleet Upptime
  introTitle: "**Wardenburg Social Uptime**"
  introMessage: Uptime Übersicht über die laufenden Dienste.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
