# Change these first
owner: m1rc0
repo: starfleetuptime

sites:
  - name: Wardenburg Social Mastodon
    url: https://masto.wardenburg.social
  - name: Wardenburg Social PeerTube
    url: https://tube.wardenburg.social
  - name: Wardenburg Social Synapse (Matrix) Server
    url: https://matrix.ocrim.de
    icon: https://matrix.org/assets/favicon.ico
  - name: Wardenburg Social Nextcloud
    url: https://cloud.wardenburg.social

status-website:
  cname: uptime.wardenburg.social
  logoUrl: https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/DEU_Wardenburg_COA.svg/800px-DEU_Wardenburg_COA.svg.png
  name: Wardenburg Social Upptime
  introTitle: "**Wardenburg Social Uptime**"
  introMessage: Uptime Übersicht über die laufenden Dienste.
  theme: ocean
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
